# encoding: utf-8

import argparse
import numpy as np
import os


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--src-dir", type=str, help="origin test dir")
    parser.add_argument("--nbest-file", type=str, help="nbest file generated by generate.py")
    parser.add_argument("--target-dir", type=str, help="target dir to store")
    args = parser.parse_args()
    
    sent_num = np.load(os.path.join(args.src_dir, "test.sent_num.npy"))
    src_file = []
    nbest_file = []
    
    print(f"reading src-file from {args.src_dir} and {args.nbest_file}")
    with open(os.path.join(args.src_dir, "test.src.txt"), "r") as f:
        for line in f:
            src_file.append(f)
        f.close()
    
    with open(args.nbest_file, "r") as f:
        for line in f:
            nbest_file.append(f)
        f.close()
    
    start_ = 0
    n_cnt = 0
    for group_idx in range(sent_num.shape[0]):
        num = int(sent_num[group_idx])
        i = 1
        while (i <= start_+num-1):
            src_file[i] = nbest_file[n_cnt]
            n_cnt += 1
    
    print(f"writing to {args.target_dir}")
    with open(args.target_dir, "w") as f:
        for line in nbest_file:
            f.write(line)
        f.close()


if __name__ == '__main__':
    main()